Update README.md
EmbarkStudios/rust-gpu pull request #135
Opened 2020-10-24 18:22 UTC by tcsian

there was some  English language problem so I fixed that problem and resubmitted that

2020-10-24 18:23 UTC, tcsian commented
Grammatical errors those fixed by me

2020-10-24 18:44 UTC, termhn requested changes

2020-10-24 18:44 UTC, termhn commented on README.md
> +Historically in games, GPU programming has been done through writing either HLSL or to a lesser extent GLSL. These are simple programming languages that have evolved along with rendering APIs over th
this comma is incorrect; there should either be no comma like the original or there should also be a comma after Historically.

2020-10-24 18:44 UTC, termhn commented on README.md
> +  - Currently, only [SPIR-V] support is planned, [Vulkan](https://en.wikipedia.org/wiki/Vulkan_(API))'s open compiler target
Should just restructure this sentence to "Currently, support is planned only for SPIR-V, Vulkan's open compiler target"

2021-01-05 09:40 UTC, XAMPPRocky commented
Going to close this as there hasn't been any activity in a couple of months and it needs to be rebased. Feel free to open a PR!

2021-01-05 09:40 UTC, closed without merging