Intercept calls to libm
EmbarkStudios/rust-gpu pull request #264
Opened 2020-11-20 08:54 UTC by khyperia

Matching on symbol names is probably not the right thing to do here, but I'm not sure what other options there are (`Instance`'s `Display` impl?).

This corresponds to a change to our `glam` PR to use libm instead of `MathExt`. Currently that's at https://github.com/EmbarkStudios/glam-rs/commit/709ac6da3cbea5a95dc52030d2237ce55aa4b50f and not merged into the `spirv` PR branch, I'll do so once this is in.

2020-11-20 11:35 UTC, eddyb commented on crates/rustc_codegen_spirv/src/builder/libm_intrinsics.rs
> +        "_ZN4libm4math6truncf6truncf17h64b5ded9471003b1E" => LibmIntrinsic::GLOp(GLOp::Trunc), // math::truncf::truncf
Looks like these are all¹ `math::$fn::$fn`, so it should be possible to grab the function name (via `tcx.item_name(def_id)`, or `tcx.def_path(def_id)` if you want the entire path at once), and check that the rest of the path conforms.

¹exceptions:
```rust
// math::erf::erfc
// math::erff::erfcf
// math::j0::y0
// math::j0f::y0f
// math::j1::y1
// math::j1f::y1f
// math::jn::yn
// math::jnf::ynf
```

2020-11-20 11:40 UTC, eddyb requested changes
LGTM, modulo the matching on mangled symbol names.

2020-11-20 12:18 UTC, eddyb commented
*(Moved here because GitHub really wanted to show 100 lines of the diff, oops)*

Looks like these are all¹ `math::$fn::$fn`, so it should be possible to grab the function name (via `tcx.item_name(def_id)`, or `tcx.def_path(def_id)` if you want the entire path at once), and check that the rest of the path conforms.

¹exceptions:
```rust
// math::erf::erfc
// math::erff::erfcf
// math::j0::y0
// math::j0f::y0f
// math::j1::y1
// math::j1f::y1f
// math::jn::yn
// math::jnf::ynf
```

2020-11-20 18:11 UTC, eddyb requested changes
r=me with the commented out line removed

2020-11-20 18:11 UTC, eddyb commented on crates/rustc_codegen_spirv/src/symbols.rs
> +    pub libm_intrinsics: HashMap<Symbol, libm_intrinsics::LibmIntrinsic>,
Almost suggested this (but forgot), nice!

2020-11-20 18:11 UTC, eddyb commented on crates/rustc_codegen_spirv/src/codegen_cx/declare.rs
> +            //let path = self.tcx.def_path(instance_def_id);
If you don't plan to use def paths, remove this?

2020-11-20 18:17 UTC, eddyb approved these changes

2020-11-20 18:35 UTC, merged

2020-11-22 02:43 UTC, termhn commented
🎉