docs: Clarify supported MoltenVK version for macOS
EmbarkStudios/rust-gpu pull request #352
Opened 2020-12-17 21:43 UTC by DeanBDean

Resolves https://github.com/EmbarkStudios/rust-gpu/issues/349

2020-12-20 23:06 UTC, eddyb commented
Made this into a draft because it turns out I was wrong about that one bug at least - see the edits to https://github.com/KhronosGroup/SPIRV-Cross/pull/1450#issuecomment-746610707.

2021-02-25 10:53 UTC, eddyb requested changes
A new release which contains a fix is now out.

2021-02-25 10:53 UTC, eddyb commented on docs/src/platform-support.md
> +| macOS | Catalina (10.15)+ | Secondary | Using [MoltenVK], requires v1.1.0+
```suggestion
| macOS | Catalina (10.15)+ | Secondary | Using [MoltenVK], requires v1.1.2+
```

as per https://github.com/EmbarkStudios/rust-gpu/issues/349#issuecomment-785804643

2021-02-25 15:53 UTC, eddyb approved these changes

2021-02-25 15:53 UTC, eddyb commented
Waiting for confirmation from anyone else (cc @khyperia as well) about whether we want to do this (including potentially adding more explanation etc.)

2021-02-26 12:04 UTC, khyperia commented
LGTM as-is, I don't think we need more explanation (linking to bugs etc.) - like, if someone really cared, they'd look at the git blame, find this PR, get the links to the relevant issues, etc., but the message this says of "things may break if below `v1.1.2`" is both accurate and I think sufficient.

2021-02-26 12:37 UTC, XAMPPRocky approved these changes

2021-02-26 13:33 UTC, VZout approved these changes

2021-02-26 13:34 UTC, merged