A whole host of minor tweaks and clippy fixes
EmbarkStudios/rust-gpu pull request #824
Opened 2021-12-13 14:35 UTC by khyperia

2021-12-13 16:54 UTC, termhn approved these changes

2021-12-13 17:06 UTC, eddyb requested changes

2021-12-13 17:06 UTC, eddyb commented on crates/rustc_codegen_spirv/src/builder/byte_addressable_buffer.rs
> +                IntoIterator::into_iter([actual_index.def(self)]),
`in_bounds_access_chain` takes `impl IntoIterator`, so I think this can just pass the array now.

2021-12-13 17:06 UTC, eddyb commented on crates/rustc_codegen_spirv/src/builder/byte_addressable_buffer.rs
> +                IntoIterator::into_iter([actual_index.def(self)]),
`in_bounds_access_chain` takes `impl IntoIterator`, so I think this can just pass the array now.

2021-12-13 17:06 UTC, eddyb commented
The test failure looks like just needs a `--bless` (line numbers, in some diagnostic, changed).

2021-12-14 07:26 UTC, khyperia commented on examples/runners/wgpu/src/compute.rs
> +        .flat_map(IntoIterator::into_iter)
Replaced with `.map(u32::to_ne_bytes).flatten()`, clippy suggested `.flat_map(u32::to_ne_bytes)`, sure I guess!

2021-12-14 07:33 UTC, eddyb approved these changes

2021-12-14 07:45 UTC, merged