Upgrade from our standard lints v4 -> v6
EmbarkStudios/rust-gpu pull request #861
Opened 2022-04-10 14:30 UTC by repi

And switches to enable them in root `.cargo/config.toml` so they are enabled for all crates in the repository. Also resolves some warnings as errors when running clippy on some of the crates that we had.

The code fixups for this was mostly from the [`clippy::single_match_else`](https://rust-lang.github.io/rust-clippy/master/#single_match_else) lint. In our other code bases we've been seeing some good improvements from the style that that enforces as avoids deeper indentation, though in this codebase the both cases look quite similar but probably doesn't hurt to just use our default.

2022-04-11 19:51 UTC, eddyb requested changes
LGTM, just one tiny nit.

2022-04-11 19:51 UTC, eddyb commented on .cargo/config
> +]
Missing newline at the end of file.

2022-04-11 19:58 UTC, repi commented on .cargo/config
> +]
hah fixed

2022-04-17 10:16 UTC, repi commented
Fixed your nit @eddyb :) 

CI fails, but currently all CI fails on Mac due to #865, so just going to merge this one

2022-04-17 10:17 UTC, merged