Upgraded compiletest_rs to 0.9.0
EmbarkStudios/rust-gpu pull request #942
Opened 2022-11-22 15:36 UTC by oisyn

2022-11-23 16:09 UTC, eddyb requested changes
LGTM modulo the weird final newline thing.

2022-11-23 16:09 UTC, eddyb commented on Cargo.toml
> +codegen-units = 256
You should e.g. "Files: Insert Final Newline" in VSCode, to fix this warning.

2022-11-24 15:10 UTC, oisyn commented
Wait why did android fail all of a sudden?

2022-11-24 15:31 UTC, eddyb approved these changes

2022-11-24 15:35 UTC, eddyb commented
> Wait why did android fail all of a sudden?

* (I assume) blocked on #945

2022-11-24 15:35 UTC, oisyn commented
> Wait why did android fail all of a sudden?

This is why: #945 🙂

2022-11-24 16:15 UTC, merged